#!/bin/bash

echo "Pre-script Info"
echo "PID: $$"

./smallsh <<___EOF___
echo
echo
echo
ls
echo
echo
ls > junk
echo
echo
cat junk
echo
echo
wc < junk
echo
echo
test -f badfile
status
echo
echo
wc < badfile
echo
echo
echo --------------------
badfile
echo
echo
echo --------------------
sleep 100 &
echo
echo
echo --------------------
pkill sleep
echo
echo
echo --------------------
sleep 1 &
sleep 1
echo
echo
echo --------------------
echo pwd
pwd
echo
echo
echo --------------------
echo cd
cd
echo
echo
echo --------------------
echo pwd (10 points for being in the HOME dir)
pwd
echo
echo
echo --------------------
echo mkdir testdir$$
mkdir testdir$$
echo
echo
echo --------------------
echo cd testdir$$
cd testdir$$
echo
echo
echo --------------------
echo pwd (10 points for being in the newly created dir)
pwd
exit
___EOF___
